DucksAndDinner/DucksAndDinner.Api/Models/CreateReservationViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DucksAndDinner.Api.Models
{
    public class CreateReservationViewModel
    {
        [DisplayName("Reservation Date")]
        public DateTime Date { get; set; }
        [DisplayName("Number of People Eating Duck")]
        public int NumberOfPeople { get; set; }
        [DisplayName("Which Duck To Eat")]
        public int DuckId { get; set; }

        public List<SelectListItem> Ducks { get; set; }
    }
}

DucksAndDinner/DucksAndDinner.Api/Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DucksAndDinner.Api.Models
{
    public class Customer
    {
        public string UserName { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Password { get; set; }

        public int NumberOfDucksPerTypicalMeal { get; set; }
    }
}

DucksAndDinner/DucksAndDinner.Api/Models/Duck.cs
namespace DucksAndDinner.Api.Models
{
    public class Duck
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Picture { get; set; }
        public int Weight { get; set; }
    }
}

DucksAndDinner/DucksAndDinner.Api/Models/Reservation.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace DucksAndDinner.Api.Models
{
    public class Reservation
    {
        [Key]
        public int Id { get; set; }

        public DateTime Date { get; set; }
        
        public int NumberOfPeople { get; set; }

        public virtual Duck DuckIAmEating { get; set; }
    }
}

DucksAndDinner/DucksAndDinner.Api/Controllers/ChickenController.cs
using System.Collections.Generic;
using System.Net;
using System.Web.Http;
using DucksAndDinner.Api.DAL;
using RestSharp;

namespace DucksAndDinner.Api.Controllers
{
    public class ChickenController : ApiController
    {
        readonly IPermitRepository _permitRepository;

        public ChickenController(IPermitRepository permitRepository)
        {
            _permitRepository = permitRepository;
        }

        public IEnumerable<Permit> GetPermits()
        {
            return _permitRepository.Get();
        }
    }

    public class ApiPermit
    {
        public string mapped_location_city { get; set; }
        public string mapped_location_state { get; set; }
        public string mapped_location_zip { get; set; }
        public string permit { get; set; }
    }

    public class Permit
    {
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string PermitNumber { get; set; }
    }
}

DucksAndDinner/DucksAndDinner.Api/Controllers/CustomerController.cs
using System.Net;
using System.Net.Http;
using System.Web.Http;
using DucksAndDinner.Api.Models;

namespace DucksAndDinner.Api.Controllers
{
    [RoutePrefix("api/customer")]
    public class CustomerController : ApiController
    {
        readonly ICustomerRepository _customerRepository;

        public CustomerController(ICustomerRepository customerRepository)
        {
            _customerRepository = customerRepository;
        }

        [HttpPost,Route]
        public HttpResponseMessage RegisterCustomer(Customer customer)
        {
            if (string.IsNullOrWhiteSpace(customer.UserName))
            {
                return Request.CreateErrorResponse(HttpStatusCode.BadRequest, "Invalid Username");
            }

            _customerRepository.Save(customer);

            return Request.CreateResponse(HttpStatusCode.OK);
        }

        [HttpGet,Route]
        public HttpResponseMessage GetAll()
        {
            var customers = _customerRepository.GetAll();

            return Request.CreateResponse(HttpStatusCode.OK, customers);
        }
    }   
}

DucksAndDinner/DucksAndDinner.Api/Controllers/DuckController.cs
using System.Web.Mvc;
using DucksAndDinner.Api.Models;

namespace DucksAndDinner.Api.Controllers
{
    public class DuckController : Controller
    {
        readonly IDuckRepository _duckRepository;

        public DuckController(IDuckRepository duckRepository)
        {
            _duckRepository = duckRepository;
        }

        // GET: Duck
        public ActionResult Index()
        {
            return View("index");
        }

        [HttpPost]
        public ActionResult BringADuck(Duck newDuck)
        {
            _duckRepository.Save(newDuck);

            return View("index");
        }
    }
}

DucksAndDinner/DucksAndDinner.Api/Controllers/ReservationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DucksAndDinner.Api.Models;

namespace DucksAndDinner.Api.Controllers
{
    public class ReservationController : Controller
    {
        readonly IReservationRepository _reservationRepository;
        readonly IDuckRepository _duckRepository;

        public ReservationController(IReservationRepository reservationRepository, IDuckRepository duckRepository)
        {
            _reservationRepository = reservationRepository;
            _duckRepository = duckRepository;
        }

        // GET: Reservation
        public ActionResult Index()
        {
            var ducks = _duckRepository.GetAll();
            var viewModel = new CreateReservationViewModel
            {
                Ducks = ducks.Select(x => new SelectListItem {Text = x.Name, Value = x.Id.ToString()}).ToList(),
                NumberOfPeople = 5,
                DuckId = 7,
                Date = new DateTime(2017,5,19)
            };

            return View("Index",viewModel);
        }

        [HttpPost]
        public ActionResult CreateReservation(CreateReservationViewModel reservation)
        {
            var res = new Reservation
            {
                Date = reservation.Date,
                NumberOfPeople = reservation.NumberOfPeople
            };

            res.DuckIAmEating = _duckRepository.Get(reservation.DuckId);

            _reservationRepository.Save(res);

            return RedirectToAction("Index");
        }
    }
}

DucksAndDinner/DucksAndDinner.Api/Views/Duck/index.cshtml
@model DucksAndDinner.Api.Models.Duck

@{
    ViewBag.Title = "Bring A Duck";
}

<h2>Bring A Duck</h2>


@using (Html.BeginForm("BringADuck","Duck",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Duck</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Picture, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Picture, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Picture, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

DucksAndDinner/DucksAndDinner.Api/Views/Reservation/Index.cshtml
@model DucksAndDinner.Api.Models.CreateReservationViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


@using (Html.BeginForm("CreateReservation","Reservation",FormMethod.Post))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CreateReservationViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Date, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Date, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Date, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumberOfPeople, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumberOfPeople, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumberOfPeople, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DuckId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.DuckId, Model.Ducks, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DuckId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

DucksAndDinner/DucksAndDinner.Api/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>